package src.java.domain;


public enum Neuron {

        PHEROMONE_GRADIENT_LEFT_RIGHT,
        PHEROMONE_GRADIENT_FORWARD,
        PHEROMONE_DENSITY,
        AGE,
        RANDOM_INPUT,
        BLOCKAGE_LEFT_RIGHT,
        OSCILLATOR,
        BLOCKAGE_FORWARD,
        POPULATION_GRADIENT_LEFT_RIGHT,
        POPULATION_DENSITY,
        POPULATION_GRADIENT_FORWARD,
        POPULATION_LONG_RANGE_FORWARD,
        LAST_MOVEMENT_Y,
        BLOCKAGE_LONG_RANGE_FORWARD,
        LAST_MOVEMENT_X,
        NORTH_SOUTH_BORDER_DISTANCE,
        GENETIC_SIMILARITY_OF_FWD_NEIGHBOR,
        EAST_WEST_BORDER_DISTANCE,
        EAST_WEST_WORLD_LOCATION,
        NEAREST_BORDER_DISTANCE,
        NORTH_SOUTH_WORLD_LOCATION,

        SET_LONG_PROBE_DISTANCE,
        KILL_FORWARD_NEIGHBOR,
        SET_OSCILLATOR_PERIOD,
        EMIT_PHEROMONE,
        SET_RESPONSIVENESS,
        MOVE_FORWARD,
        MOVE_RANDOM,
        MOVE_REVERSE,
        MOVE_LEFT_RIGHT,
        MOVE_EAST_WEST,
        MOVE_NORTH_SOUTH,

        N0,
        N1,
        N2

}

